### ISSUE TITLE
error after login in 

### ISSUE THREAD

**Issue by lucasverra** [nov/apple_id#1]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/11323803/58910341-9081cf00-8715-11e9-9e31-969cdbb3dbee.png">

I guess you need to provide a response :)

**Comment by nov** [comment]
Apple's IdP isn't stable yet. Try later.

**Comment by lucasverra** [comment]
ok, can you ping me lucas  in verra dot com . ar please ?

**Comment by nov** [comment]
Please try it by yourself.
It's working fine for my iCloud accounts.

**Comment by lucasverra** [comment]
works fine now ☺️


![image](https://user-images.githubusercontent.com/11323803/59018959-629ca780-8847-11e9-97ea-792ffc589fc4.png)
