### ISSUE TITLE
Apple's /auth/revoke not supported?

### ISSUE THREAD

**Issue by matthewkrom** [nov/apple_id#17]
Is Apple's /auth/revoke not supported? Apps submitted after June 30th 2022 may require this, depending on how Sign In With Apple is used. Thank you. Reference: `https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens`

**Comment by maierru** [comment]
```ruby
client = AppleID::Client.new(
...
)
secret = client.send(:client_secret_jwt).to_s

response = Typhoeus.post(
      "https://appleid.apple.com/auth/revoke",
      headers: {"Content-type" => "application/x-www-form-urlencoded"},
      body: {
          client_id: bundle_id,
          client_secret: secret,
          token: access_token,
          token_type_hint: "access_token"
      }
    )

raise response if !response.success?
```

**Comment by matthewkrom** [comment]
@maierru thank you ! I was on the track of sending private message `:client_secret_jwt` but hadn't completed that yet. Great to see your solution to validate the approach works for you.

**Comment by nov** [comment]
It's now supported.
https://github.com/nov/apple_id/wiki/Client#revoke-tokens

and server-to-server notification verification is also supported.
https://github.com/nov/apple_id/wiki/EventToken
