### ISSUE TITLE
Where can I find the user's email?

### ISSUE THREAD

**Issue by onato** [nov/apple_id#2]
I have the [example project](https://github.com/nov/signin-with-apple) running and I get a response after logging in but the rendered page at `/session` doesn't include the email address.

I did update the gem to 3.0 but the email field on `IdToken` is still empty.

**Comment by freestyl3r** [comment]
Keep in mind that email will be returned **only** the first time you login to a given service.
You have to revoke access through https://appleid.apple.com/account/manage if you want to receive an email again.

If this is not the case. Take a look at #3
