### ISSUE TITLE
response_mode must be form_post when name or email scope is requested

### ISSUE THREAD

**Issue by KieranP** [nov/apple_id#6]
The instructions for sending an authorisation request dont work because the url must have `&response_mode=form_post`. Without it, Apple errors out with:

`response_mode must be form_post when name or email scope is requested`

See https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms

> If you requested any scopes, the value must be form_post.

**Comment by nov** [comment]
You can specify `response_mode' when calling `AppleID::Client#authorization_uri`.
https://github.com/nov/apple_id/wiki/Client
