### ISSUE TITLE
RuntimeError (No Host Info)

### ISSUE THREAD

**Issue by bw7432** [nov/apple_id#7]
When I call `response = client.access_token!`, I get RuntimeError (No Host Info). Could someone give me some pointers here?

**Comment by nov** [comment]
Could you give me reproducible code?
Such error shouldn't happen when you're following this pattern.
https://github.com/nov/apple_id/wiki/Client

**Comment by petrbela** [comment]
I believe the client should be instantiated with `AppleID::Client.new` rather than `Rack::OAuth2::Client.new`.

I don't seem to be able to fix the wiki; @nov can you correct it pls?

**Comment by nov** [comment]
Ah, you are right.
I've fixed the doc, thanks!
